/**
 * @file non_max_supression_filter.h
 */
#ifndef Non_Max_H_
#define  Non_Max_H_

/*******************************************************************************
 * Includes
 ******************************************************************************/
#include "filter.h"
#include <vector>

/*******************************************************************************
 * Class Definitions
 ******************************************************************************/
/**
 * @brief The main class for the generation of entities.
 *
 *  The non max suppression filter takes in the direction and intensity images made by the sobel filter and
 *  uses them to generate an image with thinner edges
 * 
 */
class NonMaxSupressionFilter : public Filter {
public:

  /**
  * @brief Uses images generated by sobel filter to apply a non max supression filter.
  *
  * @return void
  */
  void Apply(std::vector<Image*>& original,std::vector<Image*>& filtered);
};



#endif
